# Stage 1 - Build Stage
FROM nginx:alpine AS builder

COPY app/index.html /tmp/index.html

# Stage 2 - Final Stage
FROM nginx:alpine

COPY --from=builder /tmp/index.html /usr/share/nginx/html/index.html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
